# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # list directory of the current directory
      - run: ls -la

      - name: Heroku Docker Container Deploy
        # You may pin to the exact commit or the version.
        # uses: lucassarcanjo/heroku-deploy@1db4c62f6032efe526c12734f18d36669218e5af
        uses: lucassarcanjo/heroku-deploy@2.1.17
        with:
          # Email Linked to your Heroku Account
          email: ${{ secrets.HEROKU_EMAIL }}
          # Heroku Dyno Formation
          # formation: # optional, default is web
          # Your Heroku API Key
          api_key: ${{ secrets.HEROKU_API_KEY }}
          # Your Heroku App Name
          app_name: ${{ secrets.HEROKU_APP_NAME }}

          # Dokerfile path
          dockerfile_path: dockerfile
          # Optional build parameters
          # options: # optional
